sudo: required

services:
  - docker

before_install:
  - docker info
  - docker version

  - docker build -f test/Dockerfile-trusty -t emacs_trusty .
  - docker build -f test/Dockerfile-xenial -t emacs_xenial .
  - docker build -f test/Dockerfile-xenial -t emacs_zesty .


script:
  - docker run emacs_trusty /usr/local/bin/emacs --version
  - docker run emacs_xenial /usr/local/bin/emacs --version
  - docker run emacs_zesty /usr/local/bin/emacs --version
