sudo: required

services:
  - docker

before_install:
  - docker info
  - docker version

  - docker build -f test/Dockerfile-trusty -t emacs_trusty .

script:
  - docker run emacs_trusty /usr/local/bin/emacs --version
